/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "include.file" instead.
 */

#include <check.h>

#include <limits.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>

#include "s21_math.h"

START_TEST(abs_test1)
{
  ck_assert_int_eq(s21_abs(0), abs(0));
  ck_assert_int_eq(s21_abs(INT_MAX), abs(INT_MAX));
  ck_assert_int_eq(s21_abs(INT_MIN), abs(INT_MIN));
  ck_assert_int_eq(s21_abs(5), abs(5));

}
END_TEST

START_TEST(abs_test2)
{
  ck_assert_int_eq(s21_abs(-1), abs(-1));
  ck_assert_int_eq(s21_abs(-0022), abs(-0022));
  ck_assert_int_eq(s21_abs(-0), abs(-0));
  ck_assert_int_eq(s21_abs(-1234), abs(-1234));

}
END_TEST

START_TEST(abs_test3)
{
  ck_assert_int_eq(s21_abs(64386876), abs(64386876));
  ck_assert_int_eq(s21_abs(-0101010), abs(-0101010));
}
END_TEST
START_TEST(acos_test_1)
{
  ck_assert_ldouble_eq_tol(s21_acos(0.0), acosl(0.0), S21_EPS);

}
END_TEST

START_TEST(acos_test_2)
{
  ck_assert_ldouble_eq_tol(s21_acos(-0.0), acosl(-0.0), S21_EPS);

}
END_TEST

START_TEST(acos_test_3)
{
  ck_assert_ldouble_eq_tol(s21_acos(-1), acosl(-1), S21_EPS);

}
END_TEST

START_TEST(acos_test_4)
{
  ck_assert_ldouble_eq_tol(s21_acos(1), acosl(1), S21_EPS);

}
END_TEST

START_TEST(acos_test_5)
{
  ck_assert_ldouble_nan(s21_acos(S21_INF));
  ck_assert_ldouble_nan(acosl(S21_INF));

}
END_TEST

START_TEST(acos_test_6)
{
  ck_assert_ldouble_nan(s21_acos(-S21_INF));
  ck_assert_ldouble_nan(acosl(-S21_INF));

}
END_TEST

START_TEST(acos_test_7)
{
  ck_assert_ldouble_nan(s21_acos(S21_NAN));
  ck_assert_ldouble_nan(acosl(S21_NAN));

}
END_TEST

START_TEST(acos_test_8)
{
  ck_assert_ldouble_nan(s21_acos(DBL_MAX));
  ck_assert_ldouble_nan(acosl(DBL_MAX));

}
END_TEST

START_TEST(acos_test_9)
{
  ck_assert_ldouble_eq_tol(s21_acos(DBL_MIN), acos(DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(acos_test_10)
{
  ck_assert_ldouble_nan(s21_acos(42352));
  ck_assert_ldouble_nan(acosl(42352));

}
END_TEST

START_TEST(acos_test_11)
{
  ck_assert_ldouble_nan(s21_acos(-35363));
  ck_assert_ldouble_nan(acosl(-35363));

}
END_TEST

START_TEST(acos_test_12)
{
  ck_assert_ldouble_eq_tol(s21_acos(0.666666), acosl(0.666666), S21_EPS);

}
END_TEST

START_TEST(acos_test_13)
{
  ck_assert_ldouble_eq_tol(s21_acos(-0.333333), acosl(-0.333333), S21_EPS);

}
END_TEST

START_TEST(acos_test_14)
{
  ck_assert_ldouble_eq_tol(s21_acos(0.999999), acosl(0.999999), S21_EPS);

}
END_TEST

START_TEST(acos_test_15)
{
  ck_assert_ldouble_eq_tol(s21_acos(-0.888), acosl(-0.888), S21_EPS);
}
END_TEST
START_TEST(asin_test_1)
{
  ck_assert_ldouble_eq_tol(s21_asin(0.0), asinl(0.0), S21_EPS);

}
END_TEST

START_TEST(asin_test_2)
{
  ck_assert_ldouble_eq_tol(s21_asin(-0.0), asinl(-0.0), S21_EPS);

}
END_TEST

START_TEST(asin_test_3)
{
  ck_assert_ldouble_eq_tol(s21_asin(-1), asinl(-1), S21_EPS);

}
END_TEST

START_TEST(asin_test_4)
{
  ck_assert_ldouble_eq_tol(s21_asin(1), asinl(1), S21_EPS);

}
END_TEST

START_TEST(asin_test_5)
{
  ck_assert_ldouble_nan(s21_asin(S21_INF));
  ck_assert_ldouble_nan(asinl(S21_INF));

}
END_TEST

START_TEST(asin_test_6)
{
  ck_assert_ldouble_nan(s21_asin(-S21_INF));
  ck_assert_ldouble_nan(asinl(-S21_INF));

}
END_TEST

START_TEST(asin_test_7)
{
  ck_assert_ldouble_nan(s21_asin(S21_NAN));
  ck_assert_ldouble_nan(asinl(S21_NAN));

}
END_TEST

START_TEST(asin_test_8)
{
  ck_assert_ldouble_nan(s21_asin(DBL_MAX));
  ck_assert_ldouble_nan(asinl(DBL_MAX));

}
END_TEST

START_TEST(asin_test_9)
{
  ck_assert_ldouble_eq_tol(s21_asin(DBL_MIN), asinl(DBL_MIN), S21_EPS);
  
}
END_TEST

START_TEST(asin_test_10)
{
  ck_assert_ldouble_nan(s21_asin(42352));
  ck_assert_ldouble_nan(asinl(42352));

}
END_TEST

START_TEST(asin_test_11)
{
  ck_assert_ldouble_nan(s21_asin(-35363));
  ck_assert_ldouble_nan(asinl(-35363));

}
END_TEST

START_TEST(asin_test_12)
{
  ck_assert_ldouble_eq_tol(s21_asin(0.666666), asinl(0.666666), S21_EPS);

}
END_TEST

START_TEST(asin_test_13)
{
  ck_assert_ldouble_eq_tol(s21_asin(-0.333333), asinl(-0.333333), S21_EPS);

}
END_TEST

START_TEST(asin_test_14)
{
  ck_assert_ldouble_eq_tol(s21_asin(0.999999), asinl(0.999999), S21_EPS);

}
END_TEST

START_TEST(asin_test_15)
{
  ck_assert_ldouble_eq_tol(s21_asin(-0.888), asinl(-0.888), S21_EPS);
}
END_TEST
START_TEST(atan_test_1)
{
  ck_assert_ldouble_eq_tol(s21_atan(0.0), atanl(0.0), S21_EPS);

}
END_TEST

START_TEST(atan_test_2)
{
  ck_assert_ldouble_eq_tol(s21_atan(-0.0), atanl(-0.0), S21_EPS);

}
END_TEST

START_TEST(atan_test_3)
{
  ck_assert_ldouble_eq_tol(s21_atan(-1), atanl(-1), S21_EPS);

}
END_TEST

START_TEST(atan_test_4)
{
  ck_assert_ldouble_eq_tol(s21_atan(1), atanl(1), S21_EPS);

}
END_TEST

START_TEST(atan_test_5)
{
  ck_assert_ldouble_eq_tol(s21_atan(S21_INF), atanl(S21_INF), S21_EPS);

}
END_TEST

START_TEST(atan_test_6)
{
  ck_assert_ldouble_eq_tol(s21_atan(-S21_INF), atanl(-S21_INF), S21_EPS);

}
END_TEST

START_TEST(atan_test_7)
{
  ck_assert_ldouble_nan(s21_atan(S21_NAN));
  ck_assert_ldouble_nan(atanl(S21_NAN));

}
END_TEST

START_TEST(atan_test_8)
{
  ck_assert_ldouble_eq_tol(s21_atan(DBL_MAX), atanl(DBL_MAX), S21_EPS);

}
END_TEST

START_TEST(atan_test_9)
{
  ck_assert_ldouble_eq_tol(s21_atan(DBL_MIN), atanl(DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(atan_test_10)
{
  ck_assert_ldouble_eq_tol(s21_atan(42352), atanl(42352), S21_EPS);

}
END_TEST

START_TEST(atan_test_11)
{
  ck_assert_ldouble_eq_tol(s21_atan(-35363), atanl(-35363), S21_EPS);

}
END_TEST

START_TEST(atan_test_12)
{
  ck_assert_ldouble_eq_tol(s21_atan(0.666666), atanl(0.666666), S21_EPS);

}
END_TEST

START_TEST(atan_test_13)
{
  ck_assert_ldouble_eq_tol(s21_atan(-0.333333), atanl(-0.333333), S21_EPS);

}
END_TEST

START_TEST(atan_test_14)
{
  ck_assert_ldouble_eq_tol(s21_atan(57434.574554256), atanl(57434.574554256), S21_EPS);

}
END_TEST

START_TEST(atan_test_15)
{
  ck_assert_ldouble_eq_tol(s21_atan(-4.574256), atanl(-4.574256), S21_EPS);
}
END_TEST
START_TEST(ceil_test_1)
{
  ck_assert_ldouble_eq(s21_ceil(0), ceill(0));
  ck_assert_ldouble_eq(s21_ceil(-0), ceill(-0));
  ck_assert_ldouble_eq(s21_ceil(-2432.3242), ceill(-2432.3242));

}
END_TEST

START_TEST(ceil_test_2)
{
  ck_assert_ldouble_eq(s21_ceil(10101010.10), ceill(10101010.10));
  ck_assert_ldouble_eq(s21_ceil(-99.999), ceill(-99.999));
  ck_assert_ldouble_eq(s21_ceil(999999.9789798), ceill(999999.9789798));
  ck_assert_ldouble_eq(s21_ceil(-56463.0), ceill(-56463.0));

}
END_TEST

START_TEST(ceil_test_3)
{
  ck_assert_ldouble_eq(s21_ceil(00034554.00034554), ceill(00034554.00034554));
  ck_assert_ldouble_eq(s21_ceil(-0.00000001), ceill(-0.00000001));

}
END_TEST

START_TEST(ceil_test_4_nan)
{
  ck_assert_ldouble_nan(s21_ceil(S21_NAN));
  ck_assert_ldouble_nan(ceill(S21_NAN));

}
END_TEST

START_TEST(ceil_test_5_inf)
{
  ck_assert_ldouble_eq(s21_ceil(S21_INF), ceill(S21_INF));
  ck_assert_ldouble_eq(s21_ceil(-S21_INF), ceill(-S21_INF));

}
END_TEST

START_TEST(ceil_test_5)
{
  ck_assert_ldouble_eq(s21_ceil(DBL_MIN), ceill(DBL_MIN));
  ck_assert_ldouble_eq(s21_ceil(-DBL_MIN), ceill(-DBL_MIN));
}
END_TEST
START_TEST(cos_test_1)
{
  for (double i = -50.0; i < 50.1; i += 0.1) {
    ck_assert_ldouble_eq_tol(s21_cos(i), cosl(i), S21_EPS);
  }

}
END_TEST

START_TEST(cos_test_2)
{
  ck_assert_ldouble_eq_tol(s21_cos(9999432424.124241), cosl(9999432424.124241), S21_EPS);

}
END_TEST

START_TEST(cos_test_3)
{
  ck_assert_ldouble_eq_tol(s21_cos(-332432.4252), cosl(-332432.4252), S21_EPS);

}
END_TEST

START_TEST(cos_test_4)
{
  ck_assert_ldouble_eq_tol(s21_cos(0), cosl(0), S21_EPS);

}
END_TEST

START_TEST(cos_test_5)
{
  ck_assert_ldouble_eq_tol(s21_cos(-0), cosl(-0), S21_EPS);

}
END_TEST

START_TEST(cos_test_6)
{
  ck_assert_ldouble_eq_tol(s21_cos(1), cosl(1), S21_EPS);

}
END_TEST

START_TEST(cos_test_7)
{
  ck_assert_ldouble_eq_tol(s21_cos(-1), cosl(-1), S21_EPS);

}
END_TEST

START_TEST(cos_test_8_nan)
{
  ck_assert_ldouble_nan(s21_cos(S21_INF));
  ck_assert_ldouble_nan(cosl(S21_INF));

}
END_TEST

START_TEST(cos_test_9_nan)
{
  ck_assert_ldouble_nan(s21_cos(-S21_INF));
  ck_assert_ldouble_nan(cosl(-S21_INF));

}
END_TEST

START_TEST(cos_test_10_nan)
{
  ck_assert_ldouble_nan(s21_cos(S21_NAN));
  ck_assert_ldouble_nan(cosl(S21_NAN));

}
END_TEST

START_TEST(cos_test_11)
{
  ck_assert_ldouble_eq(s21_cos(DBL_MIN), cosl(DBL_MIN));
}
END_TEST
START_TEST(exp_test_1)
{
  ck_assert_ldouble_eq_tol(s21_exp(1), expl(1), S21_EPS);

}
END_TEST

START_TEST(exp_test_2)
{
  ck_assert_ldouble_eq_tol(s21_exp(-1), expl(-1), S21_EPS);

}
END_TEST

START_TEST(exp_test_3)
{
  ck_assert_ldouble_eq(s21_exp(0), expl(0));

}
END_TEST

START_TEST(exp_test_4)
{
  ck_assert_ldouble_eq(s21_exp(-0), expl(-0));

}
END_TEST

START_TEST(exp_test_5_inf)
{
  ck_assert_ldouble_eq(s21_exp(999999999999), expl(999999999999));

}
END_TEST

START_TEST(exp_test_6)
{
  ck_assert_ldouble_eq_tol(s21_exp(-999999999999), expl(-999999999999), S21_EPS);

}
END_TEST

START_TEST(exp_test_7_inf)
{
  ck_assert_ldouble_eq(s21_exp(DBL_MAX), expl(DBL_MAX));

}
END_TEST

START_TEST(exp_test_8)
{
  ck_assert_ldouble_eq_tol(s21_exp(-DBL_MAX), expl(-DBL_MAX), S21_EPS);

}
END_TEST

START_TEST(exp_test_9)
{
  ck_assert_ldouble_eq_tol(s21_exp(1e-9), expl(1e-9), S21_EPSL);

}
END_TEST

START_TEST(exp_test_10)
{
  ck_assert_ldouble_eq_tol(s21_exp(-1e-9), expl(-1e-9), S21_EPSL);

}
END_TEST

START_TEST(exp_test_11)
{
  ck_assert_ldouble_eq_tol(s21_exp(DBL_MIN), expl(DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(exp_test_12)
{
  ck_assert_ldouble_eq_tol(s21_exp(DBL_MIN), expl(DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(exp_test_13)
{
  ck_assert_ldouble_eq_tol(s21_exp(-DBL_MIN), expl(-DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(exp_test_14)
{
  ck_assert_ldouble_eq(s21_exp(-S21_INF), expl(-S21_INF));

}
END_TEST

START_TEST(exp_test_15_inf)
{
  ck_assert_ldouble_eq(s21_exp(S21_INF), expl(S21_INF));

}
END_TEST

START_TEST(exp_test_16_nan)
{
  ck_assert_ldouble_nan(s21_exp(S21_NAN));
  ck_assert_ldouble_nan(expl(S21_NAN));
}
END_TEST
START_TEST(fabs_test_1)
{
  ck_assert_ldouble_eq(s21_fabs(-0.4634985729), fabsl(-0.4634985729));
  ck_assert_ldouble_eq(s21_fabs(1000.10000), fabsl(1000.1000));
  ck_assert_ldouble_eq(s21_fabs(12345.12345), fabsl(12345.12345));
  ck_assert_ldouble_eq(s21_fabs(-12345.12345), fabsl(-12345.12345));

}
END_TEST

START_TEST(fabs_test_2)
{
  ck_assert_ldouble_eq(s21_fabs(DBL_MIN), fabsl(DBL_MIN));
  ck_assert_ldouble_eq(s21_fabs(-DBL_MIN), fabsl(-DBL_MIN));
  ck_assert_ldouble_eq(s21_fabs(DBL_MAX), fabsl(DBL_MAX));
  ck_assert_ldouble_eq(s21_fabs(-DBL_MAX), fabsl(-DBL_MAX));

}
END_TEST

START_TEST(fabs_test_4)
{
  ck_assert_ldouble_nan(s21_fabs(S21_NAN));
  ck_assert_ldouble_nan(fabsl(S21_NAN));

}
END_TEST

START_TEST(fabs_test_5)
{
  ck_assert_ldouble_eq(s21_fabs(S21_INF), fabsl(S21_INF)); 
  ck_assert_ldouble_eq(s21_fabs(-S21_INF), fabsl(-S21_INF));

}
END_TEST

START_TEST(fabs_test_6)
{
  ck_assert_ldouble_eq(s21_fabs(0.0), fabsl(0.0)); 
  ck_assert_ldouble_eq(s21_fabs(-0.0), fabsl(-0.0));
}
END_TEST
START_TEST(floor_test_1)
{
  ck_assert_ldouble_eq(s21_floor(0), floorl(0));
  ck_assert_ldouble_eq(s21_floor(-0), floorl(-0));
  ck_assert_ldouble_eq(s21_floor(-2432.3242), floorl(-2432.3242));

}
END_TEST

START_TEST(floor_test_2)
{
  ck_assert_ldouble_eq(s21_floor(10101010.10), floorl(10101010.10));
  ck_assert_ldouble_eq(s21_floor(-99.999), floorl(-99.999));
  ck_assert_ldouble_eq(s21_floor(999999.9789798), floorl(999999.9789798));
  ck_assert_ldouble_eq(s21_floor(-56463.0), floorl(-56463.0));

}
END_TEST

START_TEST(floor_test_3)
{
  ck_assert_ldouble_eq(s21_floor(00034554.00034554), floorl(00034554.00034554));
  ck_assert_ldouble_eq(s21_floor(-0.00000001), floorl(-0.00000001));
  ck_assert_ldouble_eq(s21_floor(9999999999.999999), floorl(9999999999.999999));

}
END_TEST

START_TEST(floor_test_4_nan)
{
  ck_assert_ldouble_nan(s21_floor(S21_NAN));
  ck_assert_ldouble_nan(floorl(S21_NAN));

}
END_TEST

START_TEST(floor_test_5_inf)
{
  ck_assert_ldouble_eq(s21_floor(S21_INF), floorl(S21_INF));
  ck_assert_ldouble_eq(s21_floor(-S21_INF), floorl(-S21_INF));

}
END_TEST

START_TEST(floor_test_6)
{
  ck_assert_ldouble_eq(s21_floor(DBL_MIN), floorl(DBL_MIN));
  ck_assert_ldouble_eq(s21_floor(-DBL_MIN), floorl(-DBL_MIN));
}
END_TEST
START_TEST(fmod_test_nan_1)
{
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, 9.21));
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, S21_INF));
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, S21_NAN));
  ck_assert_ldouble_nan(s21_fmod(9.21, S21_NAN));
  ck_assert_ldouble_nan(s21_fmod(S21_INF, S21_NAN));

}
END_TEST

START_TEST(fmod_test_nan_1math)
{
  ck_assert_ldouble_nan(fmodl(S21_NAN, 9.21));
  ck_assert_ldouble_nan(fmodl(S21_NAN, S21_INF));
  ck_assert_ldouble_nan(fmodl(S21_NAN, S21_NAN));
  ck_assert_ldouble_nan(fmodl(9.21, S21_NAN));
  ck_assert_ldouble_nan(fmodl(S21_INF, S21_NAN));

}
END_TEST

START_TEST(fmod_test_nan_2)
{
  ck_assert_ldouble_nan(s21_fmod(-9.21, 0));
  ck_assert_ldouble_nan(s21_fmod(9.21, 0));
  ck_assert_ldouble_nan(s21_fmod(9.21, -0));
  ck_assert_ldouble_nan(s21_fmod(0, 0));
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, 0));
  ck_assert_ldouble_nan(s21_fmod(S21_NAN, -0));
  ck_assert_ldouble_nan(s21_fmod(S21_INF, 0));
  ck_assert_ldouble_nan(s21_fmod(-S21_INF, 0));

}
END_TEST

START_TEST(fmod_test_nan_2math)
{
  ck_assert_ldouble_nan(fmodl(-9.21, 0));
  ck_assert_ldouble_nan(fmodl(9.21, 0));
  ck_assert_ldouble_nan(fmodl(9.21, -0));
  ck_assert_ldouble_nan(fmodl(0, 0));
  ck_assert_ldouble_nan(fmodl(S21_NAN, 0));
  ck_assert_ldouble_nan(fmodl(S21_NAN, -0));
  ck_assert_ldouble_nan(fmodl(S21_INF, 0));
  ck_assert_ldouble_nan(fmodl(-S21_INF, 0));

}
END_TEST

START_TEST(fmod_test_nan_3)
{
  ck_assert_ldouble_nan(s21_fmod(S21_INF, S21_INF));
  ck_assert_ldouble_nan(s21_fmod(-S21_INF, S21_INF));
  ck_assert_ldouble_nan(s21_fmod(S21_INF, 1.1));
  ck_assert_ldouble_nan(s21_fmod(-S21_INF, 1.1));
  ck_assert_ldouble_nan(s21_fmod(S21_INF, -1.1));
  ck_assert_ldouble_nan(s21_fmod(-S21_INF, -1.1));
  ck_assert_ldouble_nan(s21_fmod(S21_INF, 0.00001));
  ck_assert_ldouble_nan(s21_fmod(-S21_INF, 0.00001));

}
END_TEST

START_TEST(fmod_test_nan_3math)
{
  ck_assert_ldouble_nan(fmodl(S21_INF, S21_INF));
  ck_assert_ldouble_nan(fmodl(-S21_INF, S21_INF));
  ck_assert_ldouble_nan(fmodl(S21_INF, 1.1));
  ck_assert_ldouble_nan(fmodl(-S21_INF, 1.1));
  ck_assert_ldouble_nan(fmodl(S21_INF, -1.1));
  ck_assert_ldouble_nan(fmodl(-S21_INF, -1.1));
  ck_assert_ldouble_nan(fmodl(S21_INF, 0.00001));
  ck_assert_ldouble_nan(fmodl(-S21_INF, 0.00001));

}
END_TEST

START_TEST(fmod_test_zero_1)
{
  ck_assert_ldouble_eq(s21_fmod(0, 0.00001), fmodl(0, 0.00001));

}
END_TEST

START_TEST(fmod_test_zero_2)
{
  ck_assert_ldouble_eq(s21_fmod(0, -0.00001), fmodl(0, -0.00001));

}
END_TEST

START_TEST(fmod_test_zero_3)
{
  ck_assert_ldouble_eq(s21_fmod(0, 999999999999999.9), fmodl(0, 999999999999999.9));

}
END_TEST

START_TEST(fmod_test_zero_4)
{
  ck_assert_ldouble_eq(s21_fmod(0, -999999999999999.9), fmodl(0, -999999999999999.9));

}
END_TEST

START_TEST(fmod_test_zero_5)
{
  ck_assert_ldouble_eq(s21_fmod(0, S21_INF), fmodl(0, S21_INF));

}
END_TEST

START_TEST(fmod_test_zero_6)
{
  ck_assert_ldouble_eq(s21_fmod(0, -S21_INF), fmodl(0, -S21_INF));

}
END_TEST

START_TEST(fmod_test_infinity_1)
{
  ck_assert_ldouble_eq(s21_fmod(1.0, S21_INF), fmodl(1.0, S21_INF));

}
END_TEST

START_TEST(fmod_test_infinity_2)
{
  ck_assert_ldouble_eq(s21_fmod(1.0, -S21_INF), fmodl(1.0, -S21_INF));

}
END_TEST

START_TEST(fmod_test_infinity_3)
{
  ck_assert_ldouble_eq(s21_fmod(-1.0, S21_INF), fmodl(-1.0, S21_INF));

}
END_TEST

START_TEST(fmod_test_infinity_4)
{
  ck_assert_ldouble_eq(s21_fmod(-1.0, -S21_INF), fmodl(-1.0, -S21_INF));

}
END_TEST

START_TEST(fmod_test_infinity_5)
{
  ck_assert_ldouble_eq(s21_fmod(0.0000001, S21_INF), fmodl(0.0000001, S21_INF));

}
END_TEST

START_TEST(fmod_test_infinity_6)
{
  ck_assert_ldouble_eq(s21_fmod(0.0000001, -S21_INF), fmodl(0.0000001, -S21_INF));

}
END_TEST

START_TEST(fmod_test_1)
{
  ck_assert_ldouble_eq_tol(s21_fmod(-9111111111.22222221, 0.000007), fmodl(-9111111111.22222221, 0.000007), S21_EPS);

}
END_TEST

START_TEST(fmod_test_2)
{
  ck_assert_ldouble_eq_tol(s21_fmod(9111111111.22222221, -0.000007), fmodl(9111111111.22222221, -0.000007), S21_EPS);

}
END_TEST

START_TEST(fmod_test_3)
{
  ck_assert_ldouble_eq_tol(s21_fmod(9.21, 0.000007), fmodl(9.21, 0.000007), S21_EPS);

}
END_TEST

START_TEST(fmod_test_4)
{
  ck_assert_ldouble_eq_tol(s21_fmod(-9.21, -3.7), fmodl(-9.21, -3.7), S21_EPS);

}
END_TEST

START_TEST(fmod_test_5)
{
  ck_assert_ldouble_eq_tol(s21_fmod(-9.21, -0.000007), fmodl(-9.21, -0.000007), S21_EPS);

}
END_TEST

START_TEST(fmod_test_6)
{
  ck_assert_ldouble_eq_tol(s21_fmod(9999999999999999.999999, 9999999999999999.999999), fmodl(9999999999999999.999999, 9999999999999999.999999), S21_EPS);

}
END_TEST

START_TEST(fmod_test_7)
{
  ck_assert_ldouble_eq_tol(s21_fmod(9999999999999999.999999, -9999999999999999.999999), fmodl(9999999999999999.999999, -9999999999999999.999999), S21_EPS);

}
END_TEST

START_TEST(fmod_test_8)
{
  ck_assert_ldouble_eq_tol(s21_fmod(DBL_MAX, DBL_MIN), fmodl(DBL_MAX, DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(fmod_test_9)
{
  ck_assert_ldouble_eq_tol(s21_fmod(-DBL_MAX, -DBL_MIN), fmodl(-DBL_MAX, -DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(fmod_test_10)
{
  ck_assert_ldouble_eq_tol(s21_fmod(-DBL_MAX, DBL_MIN), fmodl(-DBL_MAX, DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(fmod_test_11)
{
  ck_assert_ldouble_eq_tol(s21_fmod(DBL_MAX, -DBL_MIN), fmodl(DBL_MAX, -DBL_MIN), S21_EPS);
}
END_TEST
START_TEST(log_test_nan)
{
  ck_assert_ldouble_nan(s21_log(S21_NAN));
  ck_assert_ldouble_nan(s21_log(-S21_INF));
  ck_assert_ldouble_nan(s21_log(-DBL_MIN));
  ck_assert_ldouble_nan(s21_log(-DBL_MAX));
  ck_assert_ldouble_nan(s21_log(-3.000001));
  ck_assert_ldouble_nan(s21_log(-0.000001));

}
END_TEST

START_TEST(log_test_inf)
{
  ck_assert_ldouble_eq(s21_log(S21_INF), logl(S21_INF));
  ck_assert_ldouble_eq(s21_log(0.0), logl(0.0));
  ck_assert_ldouble_eq(s21_log(-0.0), logl(-0.0));

}
END_TEST

START_TEST(log_test_small)
{
  ck_assert_ldouble_eq_tol(s21_log(DBL_MIN), logl(DBL_MIN), S21_EPS);
  ck_assert_ldouble_eq_tol(s21_log(0.666666), logl(0.666666), S21_EPS);
  ck_assert_ldouble_eq_tol(s21_log(0.000001), logl(0.000001), S21_EPS);
  ck_assert_ldouble_eq_tol(s21_log(0.000000001), logl(0.000000001), S21_EPS);

}
END_TEST

START_TEST(log_test_big)
{
  ck_assert_ldouble_eq_tol(s21_log(DBL_MAX), logl(DBL_MAX), S21_EPS);
  ck_assert_ldouble_eq(s21_log(1.0), logl(1.0));
  ck_assert_ldouble_eq_tol(s21_log(2.0), logl(2.0), S21_EPS);
  ck_assert_ldouble_eq_tol(s21_log(22.000001), logl(22.000001), S21_EPS);
  ck_assert_ldouble_eq_tol(s21_log(123456789.666666), logl(123456789.666666), S21_EPS);
  ck_assert_ldouble_eq_tol(s21_log(6.333333e10), logl(6.333333e10), S21_EPS);
}
END_TEST
START_TEST(pow_test_nan_1)
{
  ck_assert_ldouble_nan(s21_pow(S21_NAN, 9.21));
  ck_assert_ldouble_nan(s21_pow(S21_NAN, S21_INF));
  ck_assert_ldouble_nan(s21_pow(S21_NAN, S21_NAN));
  ck_assert_ldouble_nan(s21_pow(9.21, S21_NAN));
  ck_assert_ldouble_nan(s21_pow(S21_INF, S21_NAN));

}
END_TEST

START_TEST(pow_test_nan_1math)
{
  ck_assert_ldouble_nan(powl(S21_NAN, 9.21));
  ck_assert_ldouble_nan(powl(S21_NAN, S21_INF));
  ck_assert_ldouble_nan(powl(S21_NAN, S21_NAN));
  ck_assert_ldouble_nan(powl(9.21, S21_NAN));
  ck_assert_ldouble_nan(powl(S21_INF, S21_NAN));

}
END_TEST

START_TEST(pow_test_nan_2)
{
  ck_assert_ldouble_nan(s21_pow(-9.21, 0.7));
  ck_assert_ldouble_nan(s21_pow(-9.21, -3.1));
  ck_assert_ldouble_nan(s21_pow(-1, 0.7));
  ck_assert_ldouble_nan(s21_pow(-1, -3.1));
  ck_assert_ldouble_nan(s21_pow(-0.002, 0.7));
  ck_assert_ldouble_nan(s21_pow(-0.002, 3.1));
  ck_assert_ldouble_nan(s21_pow(-9.21, -0.000007));

}
END_TEST

START_TEST(pow_test_nan_2math)
{
  ck_assert_ldouble_nan(powl(-9.21, 0.7));
  ck_assert_ldouble_nan(powl(-9.21, -3.1));
  ck_assert_ldouble_nan(powl(-1, 0.7));
  ck_assert_ldouble_nan(powl(-1, -3.1));
  ck_assert_ldouble_nan(powl(-0.002, 0.7));
  ck_assert_ldouble_nan(powl(-0.002, 3.1));
  ck_assert_ldouble_nan(powl(-9.21, -0.000007));

}
END_TEST

START_TEST(pow_test_one_1)
{
  ck_assert_ldouble_eq(s21_pow(1, 0.00001), powl(1, 0.00001));

}
END_TEST

START_TEST(pow_test_one_2)
{
  ck_assert_ldouble_eq(s21_pow(1, -5.31), powl(1, -5.31));

}
END_TEST

START_TEST(pow_test_one_3)
{
  ck_assert_ldouble_eq(s21_pow(1, DBL_MAX), powl(1, DBL_MAX));

}
END_TEST

START_TEST(pow_test_one_4)
{
  ck_assert_ldouble_eq(s21_pow(1, S21_INF), powl(1, S21_INF));

}
END_TEST

START_TEST(pow_test_one_5)
{
  ck_assert_ldouble_eq(s21_pow(1, -S21_INF), powl(1, -S21_INF));

}
END_TEST

START_TEST(pow_test_one_6)
{
  ck_assert_ldouble_eq(s21_pow(1, S21_NAN), powl(1, S21_NAN));

}
END_TEST

START_TEST(pow_test_minusone_1)
{
  ck_assert_ldouble_eq(s21_pow(-1, 2354), powl(-1, 2354));

}
END_TEST

START_TEST(pow_test_minusone_2)
{
  ck_assert_ldouble_eq(s21_pow(-1, -2354), powl(-1, -2354));

}
END_TEST

START_TEST(pow_test_minusone_3)
{
  ck_assert_ldouble_eq(s21_pow(-1, 184995), powl(-1, 184995));

}
END_TEST

START_TEST(pow_test_minusone_4)
{
  ck_assert_ldouble_eq(s21_pow(-1, -184995), powl(-1, -184995));

}
END_TEST

START_TEST(pow_test_minusone_5)
{
  ck_assert_ldouble_eq(s21_pow(-1, DBL_MAX), powl(-1, DBL_MAX));

}
END_TEST

START_TEST(pow_test_minusone_6)
{
  ck_assert_ldouble_eq(s21_pow(-1, S21_INF), powl(-1, S21_INF));

}
END_TEST

START_TEST(pow_test_minusone_7)
{
  ck_assert_ldouble_eq(s21_pow(-1, -S21_INF), powl(-1, -S21_INF));

}
END_TEST

START_TEST(pow_test_zero_1)
{
  ck_assert_ldouble_eq(s21_pow(0, 0.00001), powl(0, 0.00001));

}
END_TEST

START_TEST(pow_test_zero_2)
{
  ck_assert_ldouble_eq(s21_pow(0, -0.00001), powl(0, -0.00001));

}
END_TEST

START_TEST(pow_test_zero_3)
{
  ck_assert_ldouble_eq(s21_pow(0, 123), powl(0, 123));

}
END_TEST

START_TEST(pow_test_zero_4)
{
  ck_assert_ldouble_eq(s21_pow(0, -123), powl(0, -123));

}
END_TEST

START_TEST(pow_test_zero_5)
{
  ck_assert_ldouble_eq(s21_pow(0, 428), powl(0, 428));

}
END_TEST

START_TEST(pow_test_zero_6)
{
  ck_assert_ldouble_eq(s21_pow(0, -428), powl(0, -428));

}
END_TEST

START_TEST(pow_test_zero_7)
{
  ck_assert_ldouble_eq(s21_pow(0, 999999999999999.9), powl(0, 999999999999999.9));

}
END_TEST

START_TEST(pow_test_zero_8)
{
  ck_assert_ldouble_eq(s21_pow(0, -999999999999999.9), powl(0, -999999999999999.9));

}
END_TEST

START_TEST(pow_test_zero_9)
{
  ck_assert_ldouble_eq(s21_pow(0, S21_INF), powl(0, S21_INF));

}
END_TEST

START_TEST(pow_test_zero_10)
{
  ck_assert_ldouble_eq(s21_pow(0, -S21_INF), powl(0, -S21_INF));

}
END_TEST

START_TEST(pow_test_minuszero_1)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, 0.00001), powl(-0.0, 0.00001));

}
END_TEST

START_TEST(pow_test_minuszero_2)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, -0.00001), powl(-0.0, -0.00001));

}
END_TEST

START_TEST(pow_test_minuszero_3)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, 123), powl(-0.0, 123));

}
END_TEST

START_TEST(pow_test_minuszero_4)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, -123), powl(-0.0, -123));

}
END_TEST

START_TEST(pow_test_minuszero_5)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, 428), powl(-0.0, 428));

}
END_TEST

START_TEST(pow_test_minuszero_6)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, -428), powl(-0.0, -428));

}
END_TEST

START_TEST(pow_test_minuszero_7)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, 999999999999999.9), powl(-0.0, 999999999999999.9));

}
END_TEST

START_TEST(pow_test_minuszero_8)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, -999999999999999.9), powl(-0.0, -999999999999999.9));

}
END_TEST

START_TEST(pow_test_minuszero_9)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, S21_INF), powl(-0.0, S21_INF));

}
END_TEST

START_TEST(pow_test_minuszero_10)
{
  ck_assert_ldouble_eq(s21_pow(-0.0, -S21_INF), powl(-0.0, -S21_INF));

}
END_TEST

START_TEST(pow_test_infinity_1)
{
  ck_assert_ldouble_eq(s21_pow(S21_INF, 2357), powl(S21_INF, 2357));

}
END_TEST

START_TEST(pow_test_infinity_2)
{
  ck_assert_ldouble_eq(s21_pow(-S21_INF, 2357), powl(-S21_INF, 2357));

}
END_TEST

START_TEST(pow_test_infinity_3)
{
  ck_assert_ldouble_eq(s21_pow(S21_INF, -2357), powl(S21_INF, -2357));

}
END_TEST

START_TEST(pow_test_infinity_4)
{
  ck_assert_ldouble_eq(s21_pow(-S21_INF, -2357), powl(-S21_INF, -2357));

}
END_TEST

START_TEST(pow_test_infinity_5)
{
  ck_assert_ldouble_eq(s21_pow(S21_INF, 0.64), powl(S21_INF, 0.64));

}
END_TEST

START_TEST(pow_test_infinity_6)
{
  ck_assert_ldouble_eq(s21_pow(-S21_INF, 0.64), powl(-S21_INF, 0.64));

}
END_TEST

START_TEST(pow_test_infinity_7)
{
  ck_assert_ldouble_eq(s21_pow(S21_INF, -0.64), powl(S21_INF, -0.64));

}
END_TEST

START_TEST(pow_test_infinity_8)
{
  ck_assert_ldouble_eq(s21_pow(-S21_INF, -0.64), powl(-S21_INF, -0.64));

}
END_TEST

START_TEST(pow_test_expzero_1)
{
  ck_assert_ldouble_eq(s21_pow(0.00001, 0), powl(0.00001, 0));

}
END_TEST

START_TEST(pow_test_expzero_2)
{
  ck_assert_ldouble_eq(s21_pow(-0.00001, 0), powl(-0.00001, 0));

}
END_TEST

START_TEST(pow_test_expzero_3)
{
  ck_assert_ldouble_eq(s21_pow(123, 0), powl(123, 0));

}
END_TEST

START_TEST(pow_test_expzero_4)
{
  ck_assert_ldouble_eq(s21_pow(-123, 0), powl(-123, 0));

}
END_TEST

START_TEST(pow_test_expzero_5)
{
  ck_assert_ldouble_eq(s21_pow(999999999999999.9, 0), powl(999999999999999.9, 0));

}
END_TEST

START_TEST(pow_test_expzero_6)
{
  ck_assert_ldouble_eq(s21_pow(-999999999999999.9, 0), powl(-999999999999999.9, 0));

}
END_TEST

START_TEST(pow_test_expzero_7)
{
  ck_assert_ldouble_eq(s21_pow(S21_INF, 0), powl(S21_INF, 0));

}
END_TEST

START_TEST(pow_test_expzero_8)
{
  ck_assert_ldouble_eq(s21_pow(-S21_INF, 0), powl(-S21_INF, 0));

}
END_TEST

START_TEST(pow_test_expzero_)
{
  ck_assert_ldouble_eq(s21_pow(S21_NAN, 0), powl(S21_NAN, 0));

}
END_TEST

START_TEST(pow_test_expinfinity_1)
{
  ck_assert_ldouble_eq(s21_pow(0.05, S21_INF), powl(0.05, S21_INF));

}
END_TEST

START_TEST(pow_test_expinfinity_2)
{
  ck_assert_ldouble_eq(s21_pow(0.05, -S21_INF), powl(0.05, -S21_INF));

}
END_TEST

START_TEST(pow_test_expinfinity_3)
{
  ck_assert_ldouble_eq(s21_pow(-0.05, S21_INF), powl(-0.05, S21_INF));

}
END_TEST

START_TEST(pow_test_expinfinity_4)
{
  ck_assert_ldouble_eq(s21_pow(-0.05, -S21_INF), powl(-0.05, -S21_INF));

}
END_TEST

START_TEST(pow_test_expinfinity_5)
{
  ck_assert_ldouble_eq(s21_pow(46674.6, S21_INF), powl(46674.6, S21_INF));

}
END_TEST

START_TEST(pow_test_expinfinity_6)
{
  ck_assert_ldouble_eq(s21_pow(46674.6, -S21_INF), powl(46674.6, -S21_INF));

}
END_TEST

START_TEST(pow_test_expinfinity_7)
{
  ck_assert_ldouble_eq(s21_pow(-46674.6, S21_INF), powl(-46674.6, S21_INF));

}
END_TEST

START_TEST(pow_test_expinfinity_8)
{
  ck_assert_ldouble_eq(s21_pow(-46674.6, -S21_INF), powl(-46674.6, -S21_INF));

}
END_TEST

START_TEST(pow_test_1)
{
  ck_assert_ldouble_eq_tol(s21_pow(9.45, -894), powl(9.45, -894), S21_EPS);

}
END_TEST

START_TEST(pow_test_2)
{
  ck_assert_ldouble_eq_tol(s21_pow(237, 2.3), powl(237, 2.3), S21_EPS);

}
END_TEST

START_TEST(pow_test_3)
{
  ck_assert_ldouble_eq_tol(s21_pow(237, -0.3), powl(237, -0.3), S21_EPS);

}
END_TEST

START_TEST(pow_test_4)
{
  ck_assert_ldouble_eq_tol(s21_pow(DBL_MAX, -894), powl(DBL_MAX, -894), S21_EPS);

}
END_TEST

START_TEST(pow_test_5)
{
  ck_assert_ldouble_eq_tol(s21_pow(DBL_MAX, -0.3253), powl(DBL_MAX, -0.3253), S21_EPS);
}
END_TEST
START_TEST(sin_test_1)
{
  for (double i = -50.0; i < 50.1; i += 0.1) {
    ck_assert_ldouble_eq_tol(s21_sin(i), sinl(i), S21_EPS);
  }

}
END_TEST

START_TEST(sin_test_2)
{
  ck_assert_ldouble_eq_tol(s21_sin(9999432424.124241), sinl(9999432424.124241), S21_EPS);

}
END_TEST

START_TEST(sin_test_3)
{
  ck_assert_ldouble_eq_tol(s21_sin(-332432.4252), sinl(-332432.4252), S21_EPS);

}
END_TEST

START_TEST(sin_test_4)
{
  ck_assert_ldouble_eq_tol(s21_sin(0), sinl(0), S21_EPS);

}
END_TEST

START_TEST(sin_test_5)
{
  ck_assert_ldouble_eq_tol(s21_sin(1), sinl(1), S21_EPS);

}
END_TEST

START_TEST(sin_test_6)
{
  ck_assert_ldouble_eq_tol(s21_sin(-1), sinl(-1), S21_EPS);

}
END_TEST

START_TEST(sin_test_7_nan)
{
  ck_assert_ldouble_nan(s21_sin(S21_INF));
  ck_assert_ldouble_nan(sinl(S21_INF));

}
END_TEST

START_TEST(sin_test_8_nan)
{
  ck_assert_ldouble_nan(s21_sin(-S21_INF));
  ck_assert_ldouble_nan(sinl(-S21_INF));

}
END_TEST

START_TEST(sin_test_9_nan)
{
  ck_assert_ldouble_nan(s21_sin(S21_NAN));
  ck_assert_ldouble_nan(sinl(S21_NAN));

}
END_TEST

START_TEST(sin_test_10)
{
  ck_assert_ldouble_eq(s21_sin(DBL_MIN), sinl(DBL_MIN));
}
END_TEST
START_TEST(sqrt_test_1)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(0.0), sqrtl(0.0), S21_EPS);

}
END_TEST

START_TEST(sqrt_test_2)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(-0.0), sqrtl(-0.0), S21_EPS);  

}
END_TEST

START_TEST(sqrt_test_3)
{
  ck_assert_ldouble_nan(s21_sqrt(-1));
  ck_assert_ldouble_nan(sqrtl(-1));

}
END_TEST

START_TEST(sqrt_test_4)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(1), sqrtl(1), S21_EPS);

}
END_TEST

START_TEST(sqrt_test_5)
{
  ck_assert_ldouble_infinite(s21_sqrt(S21_INF));
  ck_assert_ldouble_infinite(sqrtl(S21_INF));

}
END_TEST

START_TEST(sqrt_test_6)
{
  ck_assert_ldouble_nan(s21_sqrt(-S21_INF));
  ck_assert_ldouble_nan(sqrtl(-S21_INF));

}
END_TEST

START_TEST(sqrt_test_7)
{
  ck_assert_ldouble_nan(s21_sqrt(S21_NAN));
  ck_assert_ldouble_nan(sqrtl(S21_NAN));

}
END_TEST

START_TEST(sqrt_test_8)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(9999999999999999.0), sqrtl(9999999999999999.0), S21_EPS);

}
END_TEST

START_TEST(sqrt_test_9)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(DBL_MIN), sqrtl(DBL_MIN), S21_EPS);

}
END_TEST

START_TEST(sqrt_test_10)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(42352), sqrtl(42352), S21_EPS);

}
END_TEST

START_TEST(sqrt_test_11)
{
  ck_assert_ldouble_nan(s21_sqrt(-35363));
  ck_assert_ldouble_nan(sqrtl(-35363));

}
END_TEST

START_TEST(sqrt_test_12)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(0.666666), sqrtl(0.666666), S21_EPS);

}
END_TEST

START_TEST(sqrt_test_13)
{
  ck_assert_ldouble_nan(s21_sqrt(-0.333333));
  ck_assert_ldouble_nan(sqrtl(-0.333333));

}
END_TEST

START_TEST(sqrt_test_14)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(10.99999), sqrtl(10.99999), S21_EPS);
  
}
END_TEST

START_TEST(sqrt_test_15)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(65.888), sqrtl(65.888), S21_EPS);

}
END_TEST

START_TEST(sqrt_test_16)
{
  ck_assert_ldouble_eq_tol(s21_sqrt(4.0), sqrtl(4.0), S21_EPS);
}
END_TEST
START_TEST(tan_test_1)
{
  for (double i = -50.0; i < 50.1; i += 0.1) {
    ck_assert_ldouble_eq_tol(s21_tan(i), tanl(i), S21_EPS);
  }
}
END_TEST

START_TEST(tan_test_2)
{
  ck_assert_ldouble_eq_tol(s21_tan(0), tanl(0), S21_EPS);

}
END_TEST

START_TEST(tan_test_3)
{
  ck_assert_ldouble_eq_tol(s21_tan(432424.1242423), tanl(432424.1242423), S21_EPS);

}
END_TEST

START_TEST(tan_test_4)
{
  ck_assert_ldouble_eq_tol(s21_tan(-332432.4252), tanl(-332432.4252), S21_EPS);

}
END_TEST

START_TEST(tan_test_5)
{
  ck_assert_ldouble_eq_tol(s21_tan(0), tanl(0), S21_EPS);

}
END_TEST

START_TEST(tan_test_6)
{
  ck_assert_ldouble_eq_tol(s21_tan(1), tanl(1), S21_EPS);

}
END_TEST

START_TEST(tan_test_7)
{
  ck_assert_ldouble_eq_tol(s21_tan(-1), tanl(-1), S21_EPS);

}
END_TEST

START_TEST(tan_test_8)
{
  ck_assert_ldouble_nan(s21_tan(S21_INF));
  ck_assert_ldouble_nan(tanl(S21_INF));

}
END_TEST

START_TEST(tan_test_9)
{
  ck_assert_ldouble_nan(s21_tan(-S21_INF));
  ck_assert_ldouble_nan(tanl(-S21_INF));

}
END_TEST

START_TEST(tan_test_10)
{
  ck_assert_ldouble_nan(s21_tan(S21_NAN));
  ck_assert_ldouble_nan(tanl(S21_NAN));

}
END_TEST

START_TEST(tan_test_11)
{
  ck_assert_ldouble_eq(s21_tan(DBL_MIN), tanl(DBL_MIN));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("abs_tests");
    TCase *tc1_1 = tcase_create("abs_tests");
    Suite *s2 = suite_create("acos_tests");
    TCase *tc2_1 = tcase_create("acos_tests");
    Suite *s3 = suite_create("asin_tests");
    TCase *tc3_1 = tcase_create("asin_tests");
    Suite *s4 = suite_create("atan_tests");
    TCase *tc4_1 = tcase_create("atan_tests");
    Suite *s5 = suite_create("ceil_tests");
    TCase *tc5_1 = tcase_create("ceil_tests");
    Suite *s6 = suite_create("cos_tests");
    TCase *tc6_1 = tcase_create("cos_tests");
    Suite *s7 = suite_create("exp_tests");
    TCase *tc7_1 = tcase_create("exp_tests");
    Suite *s8 = suite_create("fabs_tests");
    TCase *tc8_1 = tcase_create("fabs_tests");
    Suite *s9 = suite_create("floor_tests");
    TCase *tc9_1 = tcase_create("floor_tests");
    Suite *s10 = suite_create("fmod_tests");
    TCase *tc10_1 = tcase_create("fmod_tests");
    Suite *s11 = suite_create("log_tests");
    TCase *tc11_1 = tcase_create("log_tests");
    Suite *s12 = suite_create("pow_tests");
    TCase *tc12_1 = tcase_create("pow_tests");
    Suite *s13 = suite_create("sin_tests");
    TCase *tc13_1 = tcase_create("sin_tests");
    Suite *s14 = suite_create("sqrt_tests");
    TCase *tc14_1 = tcase_create("sqrt_tests");
    Suite *s15 = suite_create("tan_tests");
    TCase *tc15_1 = tcase_create("tan_tests");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, abs_test1);
    tcase_add_test(tc1_1, abs_test2);
    tcase_add_test(tc1_1, abs_test3);
    suite_add_tcase(s2, tc2_1);
    tcase_add_test(tc2_1, acos_test_1);
    tcase_add_test(tc2_1, acos_test_2);
    tcase_add_test(tc2_1, acos_test_3);
    tcase_add_test(tc2_1, acos_test_4);
    tcase_add_test(tc2_1, acos_test_5);
    tcase_add_test(tc2_1, acos_test_6);
    tcase_add_test(tc2_1, acos_test_7);
    tcase_add_test(tc2_1, acos_test_8);
    tcase_add_test(tc2_1, acos_test_9);
    tcase_add_test(tc2_1, acos_test_10);
    tcase_add_test(tc2_1, acos_test_11);
    tcase_add_test(tc2_1, acos_test_12);
    tcase_add_test(tc2_1, acos_test_13);
    tcase_add_test(tc2_1, acos_test_14);
    tcase_add_test(tc2_1, acos_test_15);
    suite_add_tcase(s3, tc3_1);
    tcase_add_test(tc3_1, asin_test_1);
    tcase_add_test(tc3_1, asin_test_2);
    tcase_add_test(tc3_1, asin_test_3);
    tcase_add_test(tc3_1, asin_test_4);
    tcase_add_test(tc3_1, asin_test_5);
    tcase_add_test(tc3_1, asin_test_6);
    tcase_add_test(tc3_1, asin_test_7);
    tcase_add_test(tc3_1, asin_test_8);
    tcase_add_test(tc3_1, asin_test_9);
    tcase_add_test(tc3_1, asin_test_10);
    tcase_add_test(tc3_1, asin_test_11);
    tcase_add_test(tc3_1, asin_test_12);
    tcase_add_test(tc3_1, asin_test_13);
    tcase_add_test(tc3_1, asin_test_14);
    tcase_add_test(tc3_1, asin_test_15);
    suite_add_tcase(s4, tc4_1);
    tcase_add_test(tc4_1, atan_test_1);
    tcase_add_test(tc4_1, atan_test_2);
    tcase_add_test(tc4_1, atan_test_3);
    tcase_add_test(tc4_1, atan_test_4);
    tcase_add_test(tc4_1, atan_test_5);
    tcase_add_test(tc4_1, atan_test_6);
    tcase_add_test(tc4_1, atan_test_7);
    tcase_add_test(tc4_1, atan_test_8);
    tcase_add_test(tc4_1, atan_test_9);
    tcase_add_test(tc4_1, atan_test_10);
    tcase_add_test(tc4_1, atan_test_11);
    tcase_add_test(tc4_1, atan_test_12);
    tcase_add_test(tc4_1, atan_test_13);
    tcase_add_test(tc4_1, atan_test_14);
    tcase_add_test(tc4_1, atan_test_15);
    suite_add_tcase(s5, tc5_1);
    tcase_add_test(tc5_1, ceil_test_1);
    tcase_add_test(tc5_1, ceil_test_2);
    tcase_add_test(tc5_1, ceil_test_3);
    tcase_add_test(tc5_1, ceil_test_4_nan);
    tcase_add_test(tc5_1, ceil_test_5_inf);
    tcase_add_test(tc5_1, ceil_test_5);
    suite_add_tcase(s6, tc6_1);
    tcase_add_test(tc6_1, cos_test_1);
    tcase_add_test(tc6_1, cos_test_2);
    tcase_add_test(tc6_1, cos_test_3);
    tcase_add_test(tc6_1, cos_test_4);
    tcase_add_test(tc6_1, cos_test_5);
    tcase_add_test(tc6_1, cos_test_6);
    tcase_add_test(tc6_1, cos_test_7);
    tcase_add_test(tc6_1, cos_test_8_nan);
    tcase_add_test(tc6_1, cos_test_9_nan);
    tcase_add_test(tc6_1, cos_test_10_nan);
    tcase_add_test(tc6_1, cos_test_11);
    suite_add_tcase(s7, tc7_1);
    tcase_add_test(tc7_1, exp_test_1);
    tcase_add_test(tc7_1, exp_test_2);
    tcase_add_test(tc7_1, exp_test_3);
    tcase_add_test(tc7_1, exp_test_4);
    tcase_add_test(tc7_1, exp_test_5_inf);
    tcase_add_test(tc7_1, exp_test_6);
    tcase_add_test(tc7_1, exp_test_7_inf);
    tcase_add_test(tc7_1, exp_test_8);
    tcase_add_test(tc7_1, exp_test_9);
    tcase_add_test(tc7_1, exp_test_10);
    tcase_add_test(tc7_1, exp_test_11);
    tcase_add_test(tc7_1, exp_test_12);
    tcase_add_test(tc7_1, exp_test_13);
    tcase_add_test(tc7_1, exp_test_14);
    tcase_add_test(tc7_1, exp_test_15_inf);
    tcase_add_test(tc7_1, exp_test_16_nan);
    suite_add_tcase(s8, tc8_1);
    tcase_add_test(tc8_1, fabs_test_1);
    tcase_add_test(tc8_1, fabs_test_2);
    tcase_add_test(tc8_1, fabs_test_4);
    tcase_add_test(tc8_1, fabs_test_5);
    tcase_add_test(tc8_1, fabs_test_6);
    suite_add_tcase(s9, tc9_1);
    tcase_add_test(tc9_1, floor_test_1);
    tcase_add_test(tc9_1, floor_test_2);
    tcase_add_test(tc9_1, floor_test_3);
    tcase_add_test(tc9_1, floor_test_4_nan);
    tcase_add_test(tc9_1, floor_test_5_inf);
    tcase_add_test(tc9_1, floor_test_6);
    suite_add_tcase(s10, tc10_1);
    tcase_add_test(tc10_1, fmod_test_nan_1);
    tcase_add_test(tc10_1, fmod_test_nan_1math);
    tcase_add_test(tc10_1, fmod_test_nan_2);
    tcase_add_test(tc10_1, fmod_test_nan_2math);
    tcase_add_test(tc10_1, fmod_test_nan_3);
    tcase_add_test(tc10_1, fmod_test_nan_3math);
    tcase_add_test(tc10_1, fmod_test_zero_1);
    tcase_add_test(tc10_1, fmod_test_zero_2);
    tcase_add_test(tc10_1, fmod_test_zero_3);
    tcase_add_test(tc10_1, fmod_test_zero_4);
    tcase_add_test(tc10_1, fmod_test_zero_5);
    tcase_add_test(tc10_1, fmod_test_zero_6);
    tcase_add_test(tc10_1, fmod_test_infinity_1);
    tcase_add_test(tc10_1, fmod_test_infinity_2);
    tcase_add_test(tc10_1, fmod_test_infinity_3);
    tcase_add_test(tc10_1, fmod_test_infinity_4);
    tcase_add_test(tc10_1, fmod_test_infinity_5);
    tcase_add_test(tc10_1, fmod_test_infinity_6);
    tcase_add_test(tc10_1, fmod_test_1);
    tcase_add_test(tc10_1, fmod_test_2);
    tcase_add_test(tc10_1, fmod_test_3);
    tcase_add_test(tc10_1, fmod_test_4);
    tcase_add_test(tc10_1, fmod_test_5);
    tcase_add_test(tc10_1, fmod_test_6);
    tcase_add_test(tc10_1, fmod_test_7);
    tcase_add_test(tc10_1, fmod_test_8);
    tcase_add_test(tc10_1, fmod_test_9);
    tcase_add_test(tc10_1, fmod_test_10);
    tcase_add_test(tc10_1, fmod_test_11);
    suite_add_tcase(s11, tc11_1);
    tcase_add_test(tc11_1, log_test_nan);
    tcase_add_test(tc11_1, log_test_inf);
    tcase_add_test(tc11_1, log_test_small);
    tcase_add_test(tc11_1, log_test_big);
    suite_add_tcase(s12, tc12_1);
    tcase_add_test(tc12_1, pow_test_nan_1);
    tcase_add_test(tc12_1, pow_test_nan_1math);
    tcase_add_test(tc12_1, pow_test_nan_2);
    tcase_add_test(tc12_1, pow_test_nan_2math);
    tcase_add_test(tc12_1, pow_test_one_1);
    tcase_add_test(tc12_1, pow_test_one_2);
    tcase_add_test(tc12_1, pow_test_one_3);
    tcase_add_test(tc12_1, pow_test_one_4);
    tcase_add_test(tc12_1, pow_test_one_5);
    tcase_add_test(tc12_1, pow_test_one_6);
    tcase_add_test(tc12_1, pow_test_minusone_1);
    tcase_add_test(tc12_1, pow_test_minusone_2);
    tcase_add_test(tc12_1, pow_test_minusone_3);
    tcase_add_test(tc12_1, pow_test_minusone_4);
    tcase_add_test(tc12_1, pow_test_minusone_5);
    tcase_add_test(tc12_1, pow_test_minusone_6);
    tcase_add_test(tc12_1, pow_test_minusone_7);
    tcase_add_test(tc12_1, pow_test_zero_1);
    tcase_add_test(tc12_1, pow_test_zero_2);
    tcase_add_test(tc12_1, pow_test_zero_3);
    tcase_add_test(tc12_1, pow_test_zero_4);
    tcase_add_test(tc12_1, pow_test_zero_5);
    tcase_add_test(tc12_1, pow_test_zero_6);
    tcase_add_test(tc12_1, pow_test_zero_7);
    tcase_add_test(tc12_1, pow_test_zero_8);
    tcase_add_test(tc12_1, pow_test_zero_9);
    tcase_add_test(tc12_1, pow_test_zero_10);
    tcase_add_test(tc12_1, pow_test_minuszero_1);
    tcase_add_test(tc12_1, pow_test_minuszero_2);
    tcase_add_test(tc12_1, pow_test_minuszero_3);
    tcase_add_test(tc12_1, pow_test_minuszero_4);
    tcase_add_test(tc12_1, pow_test_minuszero_5);
    tcase_add_test(tc12_1, pow_test_minuszero_6);
    tcase_add_test(tc12_1, pow_test_minuszero_7);
    tcase_add_test(tc12_1, pow_test_minuszero_8);
    tcase_add_test(tc12_1, pow_test_minuszero_9);
    tcase_add_test(tc12_1, pow_test_minuszero_10);
    tcase_add_test(tc12_1, pow_test_infinity_1);
    tcase_add_test(tc12_1, pow_test_infinity_2);
    tcase_add_test(tc12_1, pow_test_infinity_3);
    tcase_add_test(tc12_1, pow_test_infinity_4);
    tcase_add_test(tc12_1, pow_test_infinity_5);
    tcase_add_test(tc12_1, pow_test_infinity_6);
    tcase_add_test(tc12_1, pow_test_infinity_7);
    tcase_add_test(tc12_1, pow_test_infinity_8);
    tcase_add_test(tc12_1, pow_test_expzero_1);
    tcase_add_test(tc12_1, pow_test_expzero_2);
    tcase_add_test(tc12_1, pow_test_expzero_3);
    tcase_add_test(tc12_1, pow_test_expzero_4);
    tcase_add_test(tc12_1, pow_test_expzero_5);
    tcase_add_test(tc12_1, pow_test_expzero_6);
    tcase_add_test(tc12_1, pow_test_expzero_7);
    tcase_add_test(tc12_1, pow_test_expzero_8);
    tcase_add_test(tc12_1, pow_test_expzero_);
    tcase_add_test(tc12_1, pow_test_expinfinity_1);
    tcase_add_test(tc12_1, pow_test_expinfinity_2);
    tcase_add_test(tc12_1, pow_test_expinfinity_3);
    tcase_add_test(tc12_1, pow_test_expinfinity_4);
    tcase_add_test(tc12_1, pow_test_expinfinity_5);
    tcase_add_test(tc12_1, pow_test_expinfinity_6);
    tcase_add_test(tc12_1, pow_test_expinfinity_7);
    tcase_add_test(tc12_1, pow_test_expinfinity_8);
    tcase_add_test(tc12_1, pow_test_1);
    tcase_add_test(tc12_1, pow_test_2);
    tcase_add_test(tc12_1, pow_test_3);
    tcase_add_test(tc12_1, pow_test_4);
    tcase_add_test(tc12_1, pow_test_5);
    suite_add_tcase(s13, tc13_1);
    tcase_add_test(tc13_1, sin_test_1);
    tcase_add_test(tc13_1, sin_test_2);
    tcase_add_test(tc13_1, sin_test_3);
    tcase_add_test(tc13_1, sin_test_4);
    tcase_add_test(tc13_1, sin_test_5);
    tcase_add_test(tc13_1, sin_test_6);
    tcase_add_test(tc13_1, sin_test_7_nan);
    tcase_add_test(tc13_1, sin_test_8_nan);
    tcase_add_test(tc13_1, sin_test_9_nan);
    tcase_add_test(tc13_1, sin_test_10);
    suite_add_tcase(s14, tc14_1);
    tcase_add_test(tc14_1, sqrt_test_1);
    tcase_add_test(tc14_1, sqrt_test_2);
    tcase_add_test(tc14_1, sqrt_test_3);
    tcase_add_test(tc14_1, sqrt_test_4);
    tcase_add_test(tc14_1, sqrt_test_5);
    tcase_add_test(tc14_1, sqrt_test_6);
    tcase_add_test(tc14_1, sqrt_test_7);
    tcase_add_test(tc14_1, sqrt_test_8);
    tcase_add_test(tc14_1, sqrt_test_9);
    tcase_add_test(tc14_1, sqrt_test_10);
    tcase_add_test(tc14_1, sqrt_test_11);
    tcase_add_test(tc14_1, sqrt_test_12);
    tcase_add_test(tc14_1, sqrt_test_13);
    tcase_add_test(tc14_1, sqrt_test_14);
    tcase_add_test(tc14_1, sqrt_test_15);
    tcase_add_test(tc14_1, sqrt_test_16);
    suite_add_tcase(s15, tc15_1);
    tcase_add_test(tc15_1, tan_test_1);
    tcase_add_test(tc15_1, tan_test_2);
    tcase_add_test(tc15_1, tan_test_3);
    tcase_add_test(tc15_1, tan_test_4);
    tcase_add_test(tc15_1, tan_test_5);
    tcase_add_test(tc15_1, tan_test_6);
    tcase_add_test(tc15_1, tan_test_7);
    tcase_add_test(tc15_1, tan_test_8);
    tcase_add_test(tc15_1, tan_test_9);
    tcase_add_test(tc15_1, tan_test_10);
    tcase_add_test(tc15_1, tan_test_11);

    srunner_add_suite(sr, s2);
    srunner_add_suite(sr, s3);
    srunner_add_suite(sr, s4);
    srunner_add_suite(sr, s5);
    srunner_add_suite(sr, s6);
    srunner_add_suite(sr, s7);
    srunner_add_suite(sr, s8);
    srunner_add_suite(sr, s9);
    srunner_add_suite(sr, s10);
    srunner_add_suite(sr, s11);
    srunner_add_suite(sr, s12);
    srunner_add_suite(sr, s13);
    srunner_add_suite(sr, s14);
    srunner_add_suite(sr, s15);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
